Final version.
ASQ-USI-Elements/asq-java-q pull request #11
Opened 2016-12-16 09:41 UTC by taier1

2016-12-16 10:41 UTC, triglian requested changes
Add also comments @marcotollini in the serverside plugin file. 
example
```js
/**
 * Parses each element and returns it's database representations
* @ param {Object} The element to parse
* @return {Promise<Object>} The database representation of the question.
*/
function parseEl : coroutine(..)
```

2016-12-16 10:41 UTC, triglian commented on test/server/asqJavaqPlugin.test.js
> +      var el = $(this.tagName)[0];
give meaningful id's to the elements instead of getting them with array indices. And then do `var el = $('#mcNoInitialSettings').get(0)`

2016-12-16 10:41 UTC, triglian commented on test/server/asqJavaqPlugin.test.js
> +        expect(result.data.stem).to.equal("This is a stem <em>with some HTML</em>");
you also expect settings, right?

2016-12-16 10:41 UTC, triglian commented on test/server/asqJavaqPlugin.test.js
> +          {data:{exerciseName:'ex1',files:{main: undefined, files:[], tests:[]}}},
put the matched object in a var for readability

2016-12-16 10:41 UTC, triglian commented on test/server/asqJavaqPlugin.test.js
> +    //this.optionsHtml = fs.readFileSync(require.resolve('./fixtures/options.html'), 'utf-8');
remove if not needed

2016-12-16 10:41 UTC, triglian commented on asq-java-q.html
>         * Collect answers from inner `asq-option`s and orgnize them
the doc comment is outdated

2016-12-16 10:41 UTC, triglian commented on asq-java-q.html
> +    <asq-java-q exercise-name="exercise3" tabsize="2" compile-timeout-ms="2000" execution-timeout-ms="1" >
add docs for the important properties  (non-private) and methods.

Example: https://github.com/PolymerElements/paper-input/blob/master/paper-input-behavior.html#L36

2016-12-16 10:47 UTC, marcotollini commented on test/server/asqJavaqPlugin.test.js
> +        expect(result.data.stem).to.equal("This is a stem <em>with some HTML</em>");
No, in processEl I mock parseSettings, then I don't have any settings

2016-12-19 10:32 UTC, triglian commented on test/server/asqJavaqPlugin.test.js
> +        expect(result.data.stem).to.equal("This is a stem <em>with some HTML</em>");
you mock them so they should return a mock value

2016-12-19 10:33 UTC, triglian approved these changes

2016-12-19 10:45 UTC, merged