Added toolbar with run button.
ASQ-USI-Elements/asq-java-q pull request #8
Opened 2016-11-29 14:50 UTC by taier1

2016-11-29 15:37 UTC, BalestraPatrick requested changes

2016-11-29 15:37 UTC, BalestraPatrick commented on elements/asq-java-q-presenter.html
> +    @apply(--asq-sqlite-q-error-message);
Should replace `sqlite` with `java`

2016-12-04 16:52 UTC, triglian commented on asq-java-q.html
>  <link rel="import" href="../polymer/polymer.html">
you still have to figure out if `selectedTab` is used

2016-12-04 16:52 UTC, triglian commented on elements/asq-java-q-presenter.html
>  <link rel="import" href="../../iron-list/iron-list.html">
this element should use the  `ASQ.asqQuestionElementBehavior` like [here]( https://github.com/ASQ-USI-Elements/asq-multi-choice-q/blob/master/elements/asq-multi-choice-q-presenter.html#L121) . The same holds true for the viewer element

2016-12-05 07:51 UTC, BalestraPatrick approved these changes

2016-12-05 07:52 UTC, BalestraPatrick commented on elements/asq-java-q-presenter.html
>  <link rel="import" href="../../iron-list/iron-list.html">
Added it back. Can you please review it again so that we can merge it?

2016-12-05 07:53 UTC, BalestraPatrick commented on asq-java-q.html
>  <link rel="import" href="../polymer/polymer.html">
It's not needed at the moment.

2016-12-06 12:45 UTC, triglian requested changes

2016-12-06 12:45 UTC, triglian commented on elements/asq-java-q-viewer.html
> +      submit: function (evt) {
Submit should just submit the code as an answer.

2016-12-06 12:45 UTC, triglian commented on elements/asq-java-q-viewer.html
> +
remove commented code

2016-12-07 12:34 UTC, closed without merging