Communication frontend <-> backend
ASQ-USI-Elements/asq-java-q pull request #9
Opened 2016-12-07 12:34 UTC by BalestraPatrick

2016-12-07 13:03 UTC, triglian requested changes

2016-12-07 13:03 UTC, triglian commented on asq-java-q.html
>         * Collect answers from inner `asq-option`s and orgnize them
no asq-options anymore :-)

2016-12-07 13:03 UTC, triglian commented on test/server/asqJavaqPlugin.test.js
> +  describe.skip("parseOptions", function(){
you have to remove the options parsing. I think @marcotollini  is on it

2016-12-07 13:03 UTC, triglian commented on test/element/basic.html
>        test('test default mixin values', function() {
need. moar. tests!

Test the execute button (that you get what you want and submit it)

Also test the edge cases from when you get a response with the execution results

2016-12-07 14:50 UTC, BalestraPatrick commented on test/element/basic.html
>        test('test default mixin values', function() {
Done 👍 
Can we also have a nice Travis green badge now? 😏

2016-12-08 13:36 UTC, triglian commented on test/element/basic.html
>        test('test default mixin values', function() {
Yes add something like this https://github.com/PolymerElements/paper-input/blob/master/.travis.yml to the repo, remove the polylint dependency and command and I will add the keys

2016-12-08 16:01 UTC, BalestraPatrick commented on test/element/basic.html
>        test('test default mixin values', function() {
Just pushed it 👍

2016-12-19 07:56 UTC, closed without merging